# Generated by Django 5.0.4 on 2024-04-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='talks',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
